nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    links:
      - nextcloud:nextcloud
      - rutorrent:rutorrent
      - sickrage:sickrage
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - ./nginx/sites-enabled:/sites-enabled
      - ./nginx/conf:/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/certs:/certs
      - ./nginx/passwd:/passwds
      - ./nginx/www:/www

nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XXXX
      - MYSQL_DATABASE=XXXX
      - MYSQL_USER=XXXX
      - MYSQL_PASSWORD=XXXX

nextcloud:
    image: wonderfall/nextcloud
    container_name: nextcloud
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - REDIS_MAX_MEMORY=64mb
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
      - ADMIN_USER=XXXX
      - ADMIN_PASSWORD=XXXX
      - DB_TYPE=mysql
      - DB_NAME=XXXX
      - DB_USER=XXXX
      - DB_PASSWORD=XXXX
      - DB_HOST=nextcloud-db
    links:
      - nextcloud-db:nextcloud-db
    volumes:
      - ./nextcloud/nextcloud-data:/data
      - ./nextcloud/nextcloud-config:/config
      - ./nextcloud/nextcloud-apps:/apps2

rutorrent:
    image: xataz/rtorrent-rutorrent
    container_name: rutorrent
    volumes:
      - ./rutorrent/data:/data
    environment:
      - UID=1001
      - GID=1001
    ports:
      - "45000:45000"
      - "45000:45000/udp"
    tty: true

sickrage:
   image: xataz/sickrage
   container_name: sickrage
   volumes:
     - ./sickrage/config:/config
     - ./rutorrent/data/torrents:/torrents
     - ./sickrage/series:/series
   environment:
     - UID=1002
     - GID=1002
   links:
     - rutorrent:rutorrent
   ports:
     - "8081:8081"
